name: jaguar_orm
description: Source-generated ORM with relations (one-to-one, one-to-many, many-to-many), preloading, cascading, polymorphic relations, etc
version: 2.2.7
publish_to: none
homepage: https://github.com/Jaguar-dart/jaguar_orm
# documentation:

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  jaguar_query: # ^2.2.9
    git:
      url: https://github.com/IsaacArcadis/jaguar_orm_nullsafe.git
      path: query
  quiver: ^3.2.2
  path: ^1.9.1
  meta: ^1.17.0

dev_dependencies:
  test: ^1.31.1
