name: jaguar_query
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.2.9
homepage: https://github.com/Jaguar-dart/jaguar_orm
# documentation:

environment:
  sdk: ^3.11.5

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.31.1
